import type { Lesson } from "../types.ts";
import {
  chapter,
  click,
  demo,
  go,
  key,
  point,
  previewLine,
  projectName,
  say,
  task,
  teachTarget,
  type,
  withText,
} from "../steps.ts";

const openProjectRow = (title: Parameters<typeof withText>[1]) => [
  click(teachTarget("project-drawer"), { optional: true }),
  click(withText(teachTarget("component-row"), title)),
];

export const importExisting: Lesson = {
  id: "import",
  level: "basics",
  icon: "import",
  steps: [
    chapter("inventory"),
    go("/"),
    say("intro"),
    type(teachTarget("new-project-form", "input"), projectName, { say: "name" }),
    click(teachTarget("new-project-form", 'button[type="submit"]'), { say: "start" }),
    click(teachTarget("start-inventory"), { say: "inventory", learn: "how-to/import-an-inventory" }),
    point(teachTarget("inventory-import"), "importButton"),
    click(teachTarget("inventory-import"), { say: "importOpen" }),
    type(teachTarget("inventory-ini"), demo("ini"), { instant: true, say: "paste" }),
    point(teachTarget("inventory-counts"), "counts"),
    click(teachTarget("inventory-replace"), { say: "replace" }),
    point(withText(teachTarget("host-row"), demo("monitoredGroup")), "merged"),
    point(previewLine(demo("monitoredHeader")), "writtenBack"),
    click(teachTarget("save"), { say: "addInventory" }),
    chapter("groupVars"),
    click(teachTarget("catalog-groupvars", "button"), { say: "groupVars", learn: "how-to/group-vars" }),
    type(teachTarget("groupvars-group", "input"), demo("group"), { say: "groupName" }),
    point(teachTarget("groupvars-group"), "groupPath"),
    click(teachTarget("groupvars-yaml"), { say: "yamlMode" }),
    type(teachTarget("groupvars-yaml-text"), demo("yaml"), { instant: true, say: "yamlPaste" }),
    point(teachTarget("preview"), "yamlAsIs"),
    task("addKey", {
      checks: {
        keyTyped: withText(teachTarget("groupvars-yaml-text"), demo("taskKey")),
        keyPreviewed: previewLine(demo("taskKey")),
      },
      show: [type(teachTarget("groupvars-yaml-text"), demo("yamlWithKey"), { instant: true })],
      learn: "how-to/group-vars",
    }),
    click(teachTarget("save"), { say: "addVars" }),
    chapter("roles"),
    click('nav button[aria-expanded="false"][aria-controls$="-configure"]', { optional: true }),
    click(teachTarget("catalog-playbook", "button"), { say: "playbook", learn: "how-to/scaffold-roles" }),
    type('[data-tour="editor"] input[name="name"]', demo("playbook"), { say: "playbookName" }),
    type('[data-tour="editor"] input[name="plays.0.name"]', demo("playName"), { say: "playName" }),
    type('[data-tour="editor"] input[name="plays.0.hosts"]', demo("group"), { say: "playHosts" }),
    type(teachTarget("plays", "li [role=\"combobox\"]"), demo("role"), { say: "role", enter: true }),
    point(previewLine(demo("role")), "roleWritten"),
    say("roleChecks"),
    click(teachTarget("save"), { say: "addPlaybook" }),
    chapter("reopen"),
    say("reopenWhy"),
    ...openProjectRow(projectName),
    point(withText(teachTarget("host-address"), demo("oldAddress")), "editHost"),
    type(withText(teachTarget("host-address"), demo("oldAddress")), demo("newAddress")),
    point(previewLine(demo("newAddress")), "editPreview"),
    click(teachTarget("save"), { say: "saveChanges" }),
    task("reopenVars", {
      checks: {
        varsOpen: withText(teachTarget("groupvars-group", "input"), demo("group")),
      },
      show: openProjectRow(demo("groupVarsTitle")),
    }),
    say("reopened"),
    chapter("preset"),
    click('[data-tour="download"]', { say: "export", learn: "how-to/presets" }),
    key("Escape"),
    go("/"),
    point('[data-tour="open-preset"]', "openPreset"),
    say("done"),
  ],
};
